spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assistpyme
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update