spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assistpyme
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
mercadopago:
  access:
    token: TEST-6820296144818196-110423-e17c0175f97ce1e9f30b8039da94cae7-3143139